### PR TITLE
[L10n] Update th.po - more translations

### PR DESCRIPTION
**Pull request by bact**
- Update country names in Thai to use the official spelling from the Office of the Royal Society of Thailand
- Add some missing translations
- Fix few typos

### CODE REVIEW

**Comment by mlandres** [comment]
Thank you.

**Comment by mlandres** [comment]
JFYI: Translations for [libzypp](https://l10n.opensuse.org/projects/libzypp/master/) and [zypper](https://l10n.opensuse.org/projects/zypper/master/) are _officially_ maintained in openSUSEWeblate. Changes applied there are automatically merged back into our git and your changes applied here should be uploaded to openSUSEWeblate. So I hope nothing gets lost.

**Comment by bact** [comment]
Oh. Thank you. I should look at that instead.

(Just made PR #514 before I saw this)

Btw, a lot of translations are already avail in Unicode CLDR Project https://cldr.unicode.org/ - maybe openSUSEWeblate can utilize that as well (much better than machine translation).

**Comment by mlandres** [comment]
@bact Frankly, I don't know how Weblate is working and whether it's possible to integrate third party services. But it's a great relief for us. 

(I merged #514)

**Pull request merged**
