### PR TITLE
Rpmhead download

### PR DESCRIPTION
**Pull request by bzeller**
Teaches libzypp to download the RPM header of a package when the required information is not available. This makes it possible to see filelists and changelog from a not yet installed or upgradable package.

### CODE REVIEW

**Comment by Conan-Kudo** [comment]
@bzeller Umm, why not just fetch the filelist/other metadata instead?

**Comment by bzeller** [comment]
@Conan-Kudo not sure we have that detailed information in libsolv. But even if we do we only save a few bytes of download. We can always optimize further if we think that it is required :)

**Comment by Conan-Kudo** [comment]
@bzeller The information is available in libsolv, as we use it in libdnf through libsolv. libzypp just needs to request parsing it.

**Comment by bzeller** [comment]
@Conan-Kudo also currently the code needs to have the full rpm header at least for the filelist case, we try to not break ABI here. So we decided to stay with full header download. But I will keep your infos in mind in case we really see need to improve on that.

**Comment by Conan-Kudo** [comment]
@bzeller You don't already download the filelist.xml content instead?

**Comment by bzeller** [comment]
@Conan-Kudo no, we download only the RPM header for the requested package. The filelist is too big to download on demand , we'd need a own cache handling for that like apt-file does for example. That is out of scope for this PR, here we just wanted to extend the information you can get when querying info for a specific package. In case we ever introduce a feature to search through all available files in enabled repositories we could switch over using the available information there instead.

**Comment by bzeller** [comment]
Obsolete, if that feature would come it would be part of the zypp-ng code stream

**Pull request closed without merging**
