### PR TITLE
Fix c++-11 compiler warning

### PR DESCRIPTION
**Pull request by ya1gaurav**
By default destructors are noexcept in c++-11 so gcc compiler will give warning.
Fix applied.

### CODE REVIEW

**Comment by mlandres** [comment]
Your compiler does not require this to match the declaration in the header file? ;)

Anyway, the exception was meant to be a safety net as we started the development.  It's actually not needed and not usefull. I'd rather remove the exception than introducing `noexcept(false)`. If you like to change your PR accordingly, I'll take it.

**Comment by ya1gaurav** [comment]
So, I remove throw statement?

**Comment by mlandres** [comment]
yes

**Comment by mlandres** [comment]
@ya1gaurav Please be so kind to join those 2 commits into one. Thanks.

(E.g. `git rebase -i` and `squash` the commits using `Remove throw...` as log message.  Needs `push -f` when pushing back into your branch)

**Comment by ya1gaurav** [comment]
done in https://github.com/openSUSE/libzypp/pull/75

**Comment by mlandres** [comment]
Thanks.

(you know that you could have fixed this in branch ya1gaurav:patch-1 without need to open a new PR)

**Pull request closed without merging**
